// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tim_Udoma_Western_Insurance.Data.Models;

public partial class Buyer
{
    public int Id { get; set; }

    public Guid Reference { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedBy { get; set; }

    public string Name { get; set; }

    public string Email { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
}