// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Tim_Udoma_Western_Insurance.Data.Models;

public partial class Product
{
    public int Id { get; set; }

    public string Sku { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public int BuyerId { get; set; }

    public bool Active { get; set; }

    public DateTime DateCreated { get; set; }

    public int CreatedBy { get; set; }

    public Guid? Reference { get; set; }

    public virtual Buyer Buyer { get; set; }
}